language: python
python: 2.7
cache:
  directories:
    - eggs
    - downloads
install:
  - mkdir -p buildout-cache/downloads
  - virtualenv -p python2.7 .
  - bin/pip install -r requirements.txt
  - bin/buildout -t 30 -c travis.cfg -N
before_script:
  - export DISPLAY=:99.0
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
script:
  - bin/code-analysis
  - bin/test
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.org#imio"
    on_success: change
    on_failure: always
